/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dayCareUI;

import Classes.ClassRoom;
import Classes.School;
import Classes.Student;
import Classes.Teacher;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nithin Bharadwaj
 */
public class PendingImmunitization extends javax.swing.JPanel {

    /**
     * Creates new form PendingImmunitization
     */
    School instance;
    public PendingImmunitization() {
        initComponents();
        this.instance = School.getInstance();
        
        Vector<String> classList = new Vector<>(); 
        for (ClassRoom tk : this.instance.getClassRooms()){
            classList.add(String.valueOf(tk.getName()));
        }
        jComboClassRoom.setModel(new DefaultComboBoxModel(classList));
        
        Vector<String> teacherList = new Vector<>(); 
        for (Teacher tk : this.instance.teacherlist){
            teacherList.add(String.valueOf(tk.getId()));
        }
        jComboTeacher.setModel(new DefaultComboBoxModel(teacherList));

    }
    
    public void populateTable(List<Student> stdList) {
        DefaultTableModel dtm = (DefaultTableModel) jTblPendingStudents.getModel();
        dtm.setRowCount(0);
        for(Student pk : stdList){
            String varicella1Status = "Done";
            if(pk.getVaricella1stDose() == null){
                varicella1Status = "Pending";
            }
            String varicella2Status = "Done";
            if(pk.getVaricella2ndDose() == null){
                varicella2Status = "Pending";
            }
            String mmrVaccine1Status = "Done";
            if(pk.getMmrVaccine1stDose()== null){
                mmrVaccine1Status = "Pending";
            }
            
            String mmrVaccine2Status = "Done";
            if(pk.getMmrVaccine2ndDose()== null){
                mmrVaccine2Status = "Pending";
            }
            if(varicella1Status == "Pending" || varicella2Status == "Pending" ||
                   mmrVaccine2Status == "Pending" || mmrVaccine1Status == "Pending" ){
                
                Object [] row = new Object[6];
                row[0] = pk;
                row[1] = pk.getId();
                row[2] = mmrVaccine1Status;
                row[3] = mmrVaccine2Status;
                row[4] = varicella1Status;
                row[5] = varicella2Status;
                dtm.addRow(row);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboClassRoom = new javax.swing.JComboBox<>();
        jComboTeacher = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPendingStudents = new javax.swing.JTable();
        jbtnVaccine = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("List of Students Pending with their Vaccine Immunitization");

        jComboClassRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("ClassRoom : ");

        jLabel3.setText("Teacher :");

        jTblPendingStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student Id", "MMR Vaccine1st Dose", "MMR Vaccine 2nd Dose", "Varicella Vaccine 1st Dose", "Varicella Vaccine 2nd Dose"
            }
        ));
        jScrollPane1.setViewportView(jTblPendingStudents);

        jbtnVaccine.setText("View");
        jbtnVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVaccineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jComboClassRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jComboTeacher, 0, 107, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jbtnVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboClassRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jbtnVaccine))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVaccineActionPerformed
        // TODO add your handling code here:
        List<ClassRoom> classroomList = this.instance.getClassRooms();
        List<Teacher> teacherList = this.instance.getTeacherlist();
        System.out.println("Inside Button Click");
        for(ClassRoom cl : classroomList){
            if(cl.getName().equals(jComboClassRoom.getSelectedItem().toString())){
                System.out.println("Inside Match of classname");
                String teacherId = jComboTeacher.getSelectedItem().toString();
                for(Teacher tk : teacherList){
                    if(tk.getId() == Integer.parseInt(teacherId)){
                        this.populateTable(cl.teacherStudentGroup.get(tk));
                    }
                }
                
            }
        }
    }//GEN-LAST:event_jbtnVaccineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboClassRoom;
    private javax.swing.JComboBox<String> jComboTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblPendingStudents;
    private javax.swing.JButton jbtnVaccine;
    // End of variables declaration//GEN-END:variables
}
