/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dayCareUI;

import Classes.School;
import Classes.Student;
import Classes.Teacher;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import utility.ClearUtility;
import utility.Validation;

/**
 *
 * @author Nithin Bharadwaj
 */
public class UpdateVaccineInfo extends javax.swing.JPanel {

    /**
     * Creates new form UpdateVaccineInfo
     */
    School instance;
    public UpdateVaccineInfo() {
        initComponents();
        instance = School.getInstance();
        Vector<String> studentList = new Vector<>(); 
        for (Student tk : instance.studentlist){
            System.out.println(tk);
            studentList.add(String.valueOf(tk.getId()));
        }
        studentComboBox.setModel(new DefaultComboBoxModel(studentList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMMR1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMMR2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Vvaccine1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Vvaccine2 = new javax.swing.JTextField();
        jUpdateVaccineInfo = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE VACCINE INFO");

        jLabel2.setText("Student ID : ");

        studentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("MMR Vaccine 1st Dose :");

        jLabel5.setText("MMR Vaccine 2nd Dose :");

        jLabel6.setText("Varicella 1st Dose :");

        jLabel7.setText("Varicella 2nd Dose :");

        jUpdateVaccineInfo.setText("Update Info");
        jUpdateVaccineInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateVaccineInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUpdateVaccineInfo)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMMR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Vvaccine1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Vvaccine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMMR1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMMR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMMR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Vvaccine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Vvaccine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jUpdateVaccineInfo)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateVaccineInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateVaccineInfoActionPerformed
        // TODO add your handling code here:
        int selectedStudentId = Integer.parseInt(studentComboBox.getSelectedItem().toString());
        boolean validateMmrVaccine1 = Validation.validateDateOfBirth(txtMMR1.getText());
        boolean validateMmrVaccine2 = Validation.validateDateOfBirth(txtMMR2.getText());
        boolean validatevaricella1 = Validation.validateDateOfBirth(Vvaccine1.getText());
        boolean validatevaricella2 = Validation.validateDateOfBirth(Vvaccine2.getText());
        boolean validateVaccineInfo = validateMmrVaccine1 && validateMmrVaccine2 && validatevaricella1 && validatevaricella2 ;
        
        if(validateVaccineInfo){
            List<Student> studentInfo = instance.getStudentlist();
            for(Student pk : studentInfo){
                if(pk.getId() == selectedStudentId){
                    String mmrVacc1 = txtMMR1.getText();
                    String mmrVacc2 = txtMMR2.getText();
                    String varicella1 = Vvaccine1.getText();
                    String varicella2 = Vvaccine2.getText();

                    Date mmrVaccine1 = null;
                    try {
                        mmrVaccine1 = new SimpleDateFormat("MM-dd-yyyy").parse(mmrVacc1);
                    } catch (Exception e) {
                        System.err.println("Exception ocurred : " + e);
                    }

                    Date mmrVaccine2 = null;
                    try {
                        mmrVaccine2 = new SimpleDateFormat("MM-dd-yyyy").parse(mmrVacc2);
                    } catch (Exception e) {
                        System.err.println("Exception ocurred : " + e);
                    }

                    Date varicellaDate1 = null;
                    try {
                        varicellaDate1 = new SimpleDateFormat("MM-dd-yyyy").parse(varicella1);
                    } catch (Exception e) {
                        System.err.println("Exception ocurred : " + e);
                    }

                    Date varicellaDate2 = null;
                    try {
                        varicellaDate2 = new SimpleDateFormat("MM-dd-yyyy").parse(varicella2);
                    } catch (Exception e) {
                        System.err.println("Exception ocurred : " + e);
                    }
                    pk.setMmrVaccine1stDose(mmrVaccine1);
                    pk.setMmrVaccine2ndDose(mmrVaccine2);
                    pk.setVaricella1stDose(varicellaDate1);
                    pk.setVaricella2ndDose(varicellaDate2);
                    break;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Updated Student Vaccine Details Successfully");
            JTextField[] jk = new JTextField[] {txtMMR1, txtMMR2, 
                         Vvaccine1, Vvaccine2};
            ClearUtility.clearTextField(jk);
        }else{
            String errorMessage = String.format("Teacher info NOT SAVED!!! \n"
                    + "MMR 1st Dose valid: %s \n MMR 2nd Dose Valid : %s \n"
                    + "Varicella 1st Dose Valid : %s\n Varicella 2nd Dose Valid : %s \n"
                    ,
                    validateMmrVaccine1, validateMmrVaccine2, validatevaricella1,
                    validatevaricella2
            );
            UIManager.put("OptionPane.minimumSize", new Dimension(300, 300));
            JOptionPane.showMessageDialog(this, errorMessage);
        }
        
    }//GEN-LAST:event_jUpdateVaccineInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Vvaccine1;
    private javax.swing.JTextField Vvaccine2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jUpdateVaccineInfo;
    private javax.swing.JComboBox<String> studentComboBox;
    private javax.swing.JTextField txtMMR1;
    private javax.swing.JTextField txtMMR2;
    // End of variables declaration//GEN-END:variables
}
